In [1]:
import pandas as pd
import numpy as np

In [2]:
nav = pd.read_csv(
    "../data/raw/02_nav_history.csv"
)

print("Shape:", nav.shape)

nav.head()

Shape: (46000, 3)

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [3]:
print("Missing Values:")
print(nav.isnull().sum())

print("\nDuplicates:")
print(nav.duplicated().sum())

print("\nNAV <= 0:")
print((nav['nav'] <= 0).sum())

Missing Values:
amfi_code    0
date         0
nav          0
dtype: int64

Duplicates:
0

NAV <= 0:
0

In [4]:
nav['date'] = pd.to_datetime(
    nav['date']
)

print(nav['date'].dtype)

datetime64[us]

In [5]:
nav = nav.sort_values(
    by=['amfi_code', 'date']
)

nav.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [6]:
nav['nav'] = (
    nav.groupby('amfi_code')['nav']
    .ffill()
)

print(
    nav['nav'].isnull().sum()
)

0

In [7]:
nav.to_csv(
    "../data/processed/clean_nav.csv",
    index=False
)

print(
    "clean_nav.csv saved successfully!"
)

print(
    "Final Shape:",
    nav.shape
)

clean_nav.csv saved successfully!
Final Shape: (46000, 3)

In [8]:
transactions = pd.read_csv(
    "../data/raw/08_investor_transactions.csv"
)

print("Shape:", transactions.shape)

transactions.head()

Shape: (32778, 13)

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [9]:
print("Missing Values:")
print(
    transactions.isnull().sum()
)

print("\nDuplicates:")
print(
    transactions.duplicated().sum()
)

print("\nTransaction Types:")
print(
    transactions['transaction_type']
    .value_counts()
)

print("\nKYC Status:")
print(
    transactions['kyc_status']
    .value_counts()
)

print("\nTransactions with amount <= 0:")
print(
    (transactions['amount_inr'] <= 0)
    .sum()
)

Missing Values:
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicates:
0

Transaction Types:
transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

KYC Status:
kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

Transactions with amount <= 0:
0

In [10]:
transactions['transaction_type'] = (
    transactions['transaction_type']
    .str.strip()
    .str.title()
)

print(
    transactions['transaction_type']
    .value_counts()
)

transaction_type
Sip           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [11]:
print(
    transactions.columns.tolist()
)

['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

In [12]:
transactions['transaction_type'] = (
    transactions['transaction_type']
    .str.strip()
)

transactions['transaction_type'] = (
    transactions['transaction_type']
    .replace({
        'SIP': 'SIP',
        'Sip': 'SIP',
        'Lumpsum': 'Lumpsum',
        'Redemption': 'Redemption'
    })
)

print(
    transactions['transaction_type']
    .value_counts()
)

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [13]:
transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date']
)

print(
    transactions['transaction_date'].dtype
)

datetime64[us]

In [14]:
valid_kyc = [
    'Verified',
    'Pending'
]

invalid_kyc = transactions[
    ~transactions['kyc_status']
    .isin(valid_kyc)
]

print(
    "Invalid KYC Records:",
    len(invalid_kyc)
)

Invalid KYC Records: 0

In [15]:
transactions.to_csv(
    "../data/processed/clean_transactions.csv",
    index=False
)

print(
    "clean_transactions.csv saved successfully!"
)

print(
    "Final Shape:",
    transactions.shape
)

clean_transactions.csv saved successfully!
Final Shape: (32778, 13)

In [16]:
performance = pd.read_csv(
    "../data/raw/07_scheme_performance.csv"
)

print("Shape:", performance.shape)

performance.head()

Shape: (40, 19)

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [17]:
print(
    performance.columns.tolist()
)

['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

In [18]:
numeric_columns = [
    'return_1yr_pct',
    'return_3yr_pct',
    'return_5yr_pct',
    'benchmark_3yr_pct',
    'alpha',
    'beta',
    'sharpe_ratio',
    'sortino_ratio',
    'std_dev_ann_pct',
    'max_drawdown_pct',
    'aum_crore',
    'expense_ratio_pct'
]

performance[numeric_columns] = (
    performance[numeric_columns]
    .apply(pd.to_numeric, errors='coerce')
)

print("Missing values after numeric conversion:")
print(
    performance[numeric_columns]
    .isnull()
    .sum()
)

Missing values after numeric conversion:
return_1yr_pct       0
return_3yr_pct       0
return_5yr_pct       0
benchmark_3yr_pct    0
alpha                0
beta                 0
sharpe_ratio         0
sortino_ratio        0
std_dev_ann_pct      0
max_drawdown_pct     0
aum_crore            0
expense_ratio_pct    0
dtype: int64

In [19]:
negative_sharpe = performance[
    performance['sharpe_ratio'] < 0
]

print(
    "Funds with Negative Sharpe Ratio:",
    len(negative_sharpe)
)

if len(negative_sharpe) > 0:
    print(
        negative_sharpe[
            ['scheme_name', 'sharpe_ratio']
        ]
    )

Funds with Negative Sharpe Ratio: 0

In [20]:
invalid_expense = performance[
    (performance['expense_ratio_pct'] < 0.1)
    |
    (performance['expense_ratio_pct'] > 2.5)
]

print(
    "Funds with Invalid Expense Ratios:",
    len(invalid_expense)
)

if len(invalid_expense) > 0:
    print(
        invalid_expense[
            ['scheme_name',
             'expense_ratio_pct']
        ]
    )

Funds with Invalid Expense Ratios: 0

In [21]:
performance.to_csv(
    "../data/processed/clean_performance.csv",
    index=False
)

print(
    "clean_performance.csv saved successfully!"
)

print(
    "Final Shape:",
    performance.shape
)

clean_performance.csv saved successfully!
Final Shape: (40, 19)